service: sleep-reminder
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ap-southeast-1

functions:
  hello:
    handler: handler.remind
    events:
      - httpApi:
          path: /sleep-early
          method: get
      - schedule: cron(30 15 * * ? *) # everyday at 11.30pm SGT
